/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        primary:         'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        surface:         'var(--color-surface)',
        'surface-alt':   'var(--color-surface-alt)',
        border:          'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        'text-primary':  'var(--color-text-primary)',
        'text-secondary':'var(--color-text-secondary)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-inverse':  'var(--color-text-inverse)',
        'sidebar-bg':          'var(--sidebar-bg)',
        'sidebar-text':        'var(--sidebar-text)',
        'sidebar-text-active': 'var(--sidebar-text-active)',
        'sidebar-item-hover':  'var(--sidebar-item-hover)',
        'sidebar-item-active': 'var(--sidebar-item-active-bg)',
        'sidebar-accent':      'var(--sidebar-accent)',
        error:           'var(--color-error)',
        'error-light':   'var(--color-error-light)',
        success:         'var(--color-success)',
        'success-light': 'var(--color-success-light)',
        warning:         'var(--color-warning)',
        'warning-light': 'var(--color-warning-light)',
      },
      fontFamily: {
        sans: 'var(--font-family-sans)',
        mono: 'var(--font-family-mono)',
      },
      fontSize: {
        xs:   'var(--font-size-xs)',
        sm:   'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg:   'var(--font-size-lg)',
        xl:   'var(--font-size-xl)',
        '2xl':'var(--font-size-2xl)',
        '3xl':'var(--font-size-3xl)',
        '4xl':'var(--font-size-4xl)',
      },
      borderRadius: {
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
    },
  },
  plugins: [require('tailwindcss-primeui')],
}