// <auto-generated />
using System;
using GOP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GOP.Infrastructure.Migrations
{
    [DbContext(typeof(GopDbContext))]
    [Migration("20260416155717_InitialWellsAndCatalogs")]
    partial class InitialWellsAndCatalogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GOP.Domain.Entities.Campo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Campos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContratoId = 1,
                            Nombre = "Campo Rubiales"
                        },
                        new
                        {
                            Id = 2,
                            ContratoId = 1,
                            Nombre = "Campo Quifa"
                        },
                        new
                        {
                            Id = 3,
                            ContratoId = 2,
                            Nombre = "Campo Cusiana"
                        },
                        new
                        {
                            Id = 4,
                            ContratoId = 2,
                            Nombre = "Campo Cupiagua"
                        },
                        new
                        {
                            Id = 5,
                            ContratoId = 3,
                            Nombre = "Campo Lisama"
                        },
                        new
                        {
                            Id = 6,
                            ContratoId = 3,
                            Nombre = "Campo La Cira"
                        });
                });

            modelBuilder.Entity("GOP.Domain.Entities.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CampoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CampoId");

                    b.ToTable("Clusters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampoId = 1,
                            Nombre = "Cluster Norte"
                        },
                        new
                        {
                            Id = 2,
                            CampoId = 1,
                            Nombre = "Cluster Sur"
                        },
                        new
                        {
                            Id = 3,
                            CampoId = 3,
                            Nombre = "Cluster Este"
                        },
                        new
                        {
                            Id = 4,
                            CampoId = 3,
                            Nombre = "Cluster Oeste"
                        });
                });

            modelBuilder.Entity("GOP.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Cuenca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Contratos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuenca = "Llanos Orientales",
                            Nombre = "Contrato E&P Llanos",
                            Tipo = "E&P"
                        },
                        new
                        {
                            Id = 2,
                            Cuenca = "Piedemonte Llanero",
                            Nombre = "Contrato E&P Piedemonte",
                            Tipo = "E&P"
                        },
                        new
                        {
                            Id = 3,
                            Cuenca = "Valle Medio del Magdalena",
                            Nombre = "Contrato E&P Magdalena",
                            Tipo = "E&P"
                        });
                });

            modelBuilder.Entity("GOP.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDane")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoDane = "50",
                            Nombre = "Meta"
                        },
                        new
                        {
                            Id = 2,
                            CodigoDane = "85",
                            Nombre = "Casanare"
                        },
                        new
                        {
                            Id = 3,
                            CodigoDane = "68",
                            Nombre = "Santander"
                        });
                });

            modelBuilder.Entity("GOP.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDane")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoDane = "50568",
                            DepartamentoId = 1,
                            Nombre = "Puerto Gaitán"
                        },
                        new
                        {
                            Id = 2,
                            CodigoDane = "50001",
                            DepartamentoId = 1,
                            Nombre = "Villavicencio"
                        },
                        new
                        {
                            Id = 3,
                            CodigoDane = "85001",
                            DepartamentoId = 2,
                            Nombre = "Yopal"
                        },
                        new
                        {
                            Id = 4,
                            CodigoDane = "85010",
                            DepartamentoId = 2,
                            Nombre = "Aguazul"
                        },
                        new
                        {
                            Id = 5,
                            CodigoDane = "68081",
                            DepartamentoId = 3,
                            Nombre = "Barrancabermeja"
                        },
                        new
                        {
                            Id = 6,
                            CodigoDane = "68001",
                            DepartamentoId = 3,
                            Nombre = "Bucaramanga"
                        });
                });

            modelBuilder.Entity("GOP.Domain.Entities.Well", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CampoId")
                        .HasColumnType("int");

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Consecutivo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuenca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePozo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Operadora")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAngulo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoObjetivo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TipoTerminacion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TipoTrayectoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoUbicacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CampoId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Wells_TenantId");

                    b.ToTable("Wells", (string)null);
                });

            modelBuilder.Entity("GOP.Domain.Entities.Campo", b =>
                {
                    b.HasOne("GOP.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Campos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("GOP.Domain.Entities.Cluster", b =>
                {
                    b.HasOne("GOP.Domain.Entities.Campo", "Campo")
                        .WithMany("Clusters")
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campo");
                });

            modelBuilder.Entity("GOP.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("GOP.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("GOP.Domain.Entities.Well", b =>
                {
                    b.HasOne("GOP.Domain.Entities.Campo", null)
                        .WithMany()
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GOP.Domain.Entities.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("GOP.Domain.Entities.WellLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("WellId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("ClusterId")
                                .HasColumnType("int")
                                .HasColumnName("ClusterId");

                            b1.Property<string>("CodigoDaneDpto")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("CodigoDaneDpto");

                            b1.Property<string>("CodigoDaneMpio")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("CodigoDaneMpio");

                            b1.Property<int>("DepartamentoId")
                                .HasColumnType("int")
                                .HasColumnName("DepartamentoId");

                            b1.Property<int>("MunicipioId")
                                .HasColumnType("int")
                                .HasColumnName("MunicipioId");

                            b1.HasKey("WellId");

                            b1.ToTable("Wells");

                            b1.WithOwner()
                                .HasForeignKey("WellId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("GOP.Domain.Entities.Campo", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("GOP.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Campos");
                });

            modelBuilder.Entity("GOP.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
