<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>GOP.API</AssemblyName>
    <RootNamespace>GOP.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GOP.Application\GOP.Application.csproj" />
    <ProjectReference Include="..\GOP.Infrastructure\GOP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.*" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.*" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.*" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.*" />
  </ItemGroup>

</Project>
